name: Sedstart Local Windows

on:
  workflow_dispatch:

jobs:
  sedstart-run:
    runs-on: windows-latest
    steps:
      - name: Install Playwright
        run: npm install -g playwright@1.52.0

      - name: Trigger SedStart test run
        uses: sedstart/runlocal@main
        with:
          api_key: ${{ secrets.SEDSTART_API_KEY_QA }}
          project_id: 503
          test_id: 3449
          browser: chrome
          headless: false
          environment: 'QA'

